#!/usr/bin/env bash

purpose="Hw prints hello world!"
version=0.0.0

case "${1}" in
	-h|--help)
		echo "${purpose}"
		echo ""
		echo "usage: hw [opts]"
		echo ""
		echo "Options:"
		echo ""
		echo "	-h, --help		Print this message"
		echo "	-V, --version		Print the version"
		;;
	-V|--version)
		echo "hw version ${version}"
		;;
	*)
		echo "hello world!"
		;;
esac
